"""empty message

Revision ID: 5cc563b5df45
Revises: 7c1e3e1d149e
Create Date: 2025-02-02 01:11:29.708096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '5cc563b5df45'
down_revision: Union[str, None] = '7c1e3e1d149e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('number', sa.Column('age', sa.Integer(), nullable=True))  # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('number', 'age')  # ### end Alembic commands ###
