"""empty message

Revision ID: 7c1e3e1d149e
Revises: ffe5ad92504b
Create Date: 2025-02-02 01:11:13.138370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '7c1e3e1d149e'
down_revision: Union[str, None] = 'ffe5ad92504b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass  # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass  # ### end Alembic commands ###
