"""empty message

Revision ID: bfdc52fd4864
Revises: ee71d38aba69
Create Date: 2025-02-02 01:08:49.070254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'bfdc52fd4864'
down_revision: Union[str, None] = 'ee71d38aba69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass  # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass  # ### end Alembic commands ###
