"""empty message

Revision ID: c2d2e621820a
Revises: e717cbaee177
Create Date: 2025-02-02 11:43:32.671874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'c2d2e621820a'
down_revision: Union[str, None] = 'e717cbaee177'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('number', sa.Column('age', sa.Integer(), nullable=True))  # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('number', 'age')  # ### end Alembic commands ###
