"""empty message

Revision ID: c588132e98a3
Revises: 5cc563b5df45
Create Date: 2025-02-02 11:10:42.198549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'c588132e98a3'
down_revision: Union[str, None] = '5cc563b5df45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass  # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass  # ### end Alembic commands ###
