"""empty message

Revision ID: dc7ed0eb6084
Revises: c588132e98a3
Create Date: 2025-02-02 11:11:36.230920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'dc7ed0eb6084'
down_revision: Union[str, None] = 'c588132e98a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('number', 'age')  # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('number', sa.Column('age', mysql.INTEGER(), autoincrement=False, nullable=True))  # ### end Alembic commands ###
