"""empty message

Revision ID: e717cbaee177
Revises: dc7ed0eb6084
Create Date: 2025-02-02 11:42:48.665285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'e717cbaee177'
down_revision: Union[str, None] = 'dc7ed0eb6084'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass  # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass  # ### end Alembic commands ###
