"""empty message

Revision ID: ee71d38aba69
Revises: f7e825a4384f
Create Date: 2025-02-02 01:08:15.995915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'ee71d38aba69'
down_revision: Union[str, None] = 'f7e825a4384f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('number', sa.Column('number', sa.Integer(), nullable=False), sa.PrimaryKeyConstraint('number'))  # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('number')  # ### end Alembic commands ###
