"""empty message

Revision ID: f7e825a4384f
Revises: 3feea2cfe20f
Create Date: 2025-02-02 01:07:53.858446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f7e825a4384f'
down_revision: Union[str, None] = '3feea2cfe20f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('number')  # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('number', sa.Column('number', mysql.INTEGER(), autoincrement=True, nullable=False), sa.Column('age', mysql.INTEGER(), autoincrement=False, nullable=True), sa.PrimaryKeyConstraint('number'), mysql_collate='utf8mb4_0900_ai_ci', mysql_default_charset='utf8mb4', mysql_engine='InnoDB')  # ### end Alembic commands ###
