"""empty message

Revision ID: ffe5ad92504b
Revises: bfdc52fd4864
Create Date: 2025-02-02 01:09:01.739685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'ffe5ad92504b'
down_revision: Union[str, None] = 'bfdc52fd4864'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass  # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass  # ### end Alembic commands ###
